services:
  app:
    image: teddy-teste-backend-image
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: sh -c "npx prisma migrate deploy && node main.js"
    container_name: teddy-teste-backend
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - teddy-teste-network
    env_file:
      - .env

  db:
    container_name: teddy-teste-database
    image: postgres
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 3020:5432
    networks:
      - teddy-teste-network

networks:
  teddy-teste-network:
    driver: bridge
